
def main():
    print(open('customException.py','r').read())

if __name__ == '__main__':
    main()

    #from subprocess import call
    #call(["python", "customException.py"])
    #exec(open('customException.py','r').read())